### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by akshayjamwal07** [ryanatwork/hacker_news_search#8]
Hi,

I created an Angular project to queryy hacker search API for practise. I am getting CORS issue when i request for articles. Can you please have a look at it?

See the exception stacktrace below- 

OPTIONS https://hn.algolia.com/?query=&sort=byPopularity&prefix=&page=0&dateRange=All&type=story 404
Access to XMLHttpRequest at 'https://hn.algolia.com/?query=&sort=byPopularity&prefix=&page=0&dateRange=All&type=story' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
core.js:9110 ERROR Something bad happened; please try again later.

**Comment by ryanatwork** [comment]
The README states that this library no longer works. Please look for another library that fits your needs.
